FROM golang:1.26.2-alpine AS builder
RUN apk add --no-cache git ca-certificates && update-ca-certificates
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/rest-server ./cmd/server/main.go

FROM alpine:3.19
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
WORKDIR /app
COPY --from=builder /app/rest-server .
USER appuser
EXPOSE 5000
CMD ["./rest-server"]
