// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Create a JWT token for user",
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.signUpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account with student role",
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.signUpInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.loginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/level": {
            "get": {
                "description": "Retrieve a list of all levels, optionally including their steps",
                "tags": [
                    "levels"
                ],
                "summary": "Get all levels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/chinese-game-backend_internal_domain.Level"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_transport_http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "chinese-game-backend_internal_domain.DialogStepItem": {
            "type": "object",
            "properties": {
                "bg": {
                    "type": "string"
                },
                "emotion": {
                    "type": "string"
                },
                "speaker": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "chinese-game-backend_internal_domain.Level": {
            "type": "object",
            "properties": {
                "background_src": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order_index": {
                    "type": "integer"
                },
                "planet_img_src": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chinese-game-backend_internal_domain.LevelStep"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "chinese-game-backend_internal_domain.LevelStep": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "dialog": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/chinese-game-backend_internal_domain.DialogStepItem"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "level_id": {
                    "type": "integer"
                },
                "order_index": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/chinese-game-backend_internal_domain.LevelStepType"
                }
            }
        },
        "chinese-game-backend_internal_domain.LevelStepType": {
            "type": "string",
            "enum": [
                "theory",
                "quiz",
                "final",
                "dialog",
                "categorization",
                "tone_listening",
                "planet_click",
                "planet_matching"
            ],
            "x-enum-varnames": [
                "LevelStepThoery",
                "LevelStepQuiz",
                "LevelStepFinal",
                "LevelStepDialog",
                "LevelStepCategoriz",
                "LevelStepToneListen",
                "LevelStepPlanetClick",
                "LevelStepPlanetMatch"
            ]
        },
        "internal_transport_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.loginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_transport_http.signUpInput": {
            "type": "object",
            "properties": {
                "invite_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:5000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Chinese Game API",
	Description:      "API for web game for learning Chinese",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
